image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2

build:
  stage: build
  script:
    - docker build -t my-app .
    - docker save my-app | gzip > my-app.tar.gz
  artifacts:
    paths:
      - my-app.tar.gz

test:
  stage: test
  script:
    - docker load < my-app.tar.gz
    - docker run --rm my-app npm test

deploy:
  stage: deploy
  script:
    - echo "Deploying to server"
    # Add your deployment script here, e.g., rsync or SSH commands
  only:
    - main
